CREATE DATABASE storeDB;
USE storeDB;

CREATE TABLE categories (
    category_id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL UNIQUE
);

INSERT INTO categories (name) VALUES
('table'),
('utensils'),
('decoration'),
('lighting'),
('sofa'),
('tv unit'),
('pillow'),
('rug'),
('side table'),
('curtain'),
('bed'),
('wardrobe'),
('box');

CREATE TABLE products (
    product_id INT PRIMARY KEY,
    product_name VARCHAR(255),
    product_model VARCHAR(255),
    product_serial_number VARCHAR(255),
    product_main_category VARCHAR(255),
    product_category VARCHAR(255),
    product_material VARCHAR(255),
    product_color VARCHAR(255),
    product_features VARCHAR(255),
    product_stock INT,
    product_price INT,
    product_image VARCHAR(255),
    product_comment VARCHAR(255),
    product_rating INT 
);


INSERT INTO products 
(product_id, product_name, product_main_category, product_category, product_material, product_color, product_features, product_stock, product_price, product_image, product_comment, product_rating)
VALUES
(10001, 'Paris Table', 'kitchen, living room, bedroom', 'table', 'wood', 'beige', '140x78 cm, 4 seats', 50, 9000, 'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10001.png','',''),
(10002, 'Berlin Table', 'kitchen, living room, bedroom', 'table', 'plastic', 'white', '120x80 cm, 6 seats', 30, 3000, 'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10002.png','',''),
(10003, 'Amsterdam Table', 'kitchen', 'table', 'wood', 'brown', '100x60 cm, 4 seats', 15, 4000, 'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10003.png','',''),
(10004, 'Rome Table', 'kitchen, living room', 'table', 'wood', 'beige', '120 cm, 4 seats, round, folding', 40, 15000, 'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10004.png','',''),
(10005, 'Helsinki Table', 'kitchen', 'table', 'plastic, metal', 'black, gray', '67x67 cm, 2 seats, folding', 60, 1700, 'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10005.png','',''),
(10006, 'Paris Chair', 'living room, bedroom', 'chair', 'wood', 'white', 'soft cushion, ergonomic', 80, 2500, 'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10006.png','',''),
(10007, 'Tech Chair', 'living room, bedroom', 'chair', 'metal', 'black', 'leather surface, durable', 55, 3200, 'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10007.png','',''),
(10008, 'Berlin Chair', 'living room', 'chair', 'wood', 'brown', 'minimalist, lightweight', 35, 2100, 'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10008.png','',''),
(10009, 'Amsterdam Chair', 'kitchen, living room', 'chair', 'plastic', 'gray', 'stackable, modern design', 120, 900, 'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10009.png','',''),
(10010, 'Balat Chair', 'living room, bedroom', 'chair', 'metal, plastic', 'white', 'set of 4 chairs', 25, 5000, 'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10010.png','',''),
(10011, 'Pot Set', 'kitchen', 'utensils', 'metal', 'gray', 'durable, 5 pieces', 100, 6000, 'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10011.png','',''),
(10012, 'Glove', 'kitchen', 'utensils', 'fabric', 'red', 'heat resistant', 150, 300, 'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10012.png','',''),
(10013, 'Helper', 'kitchen', 'utensils', 'metal', 'silver', 'multi-functional tool', 85, 450, 'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10013.png','', ''),
(10014, 'Plate Set', 'kitchen, living room', 'utensils', 'ceramic', 'white', 'set of 6 plates', 65, 800, 'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10014.png','',''),
(10015, 'Service', 'kitchen', 'utensils', 'ceramic', 'blue', '4 bowls, microwave safe', 75, 1100, 'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10015.png','',''),
(10016, 'Mirror', 'bedroom', 'decoration', 'metal', 'yellow', 'on-stand', 20, 2400, 'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10016.png','',''),
(10017,'Cat','kitchen, living room, bedroom, bathroom','decoration','glass','black','1 piece',15,100,'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10017.png','',''),
(10018,'Birds','kitchen, living room, bedroom','decoration','metal','gray','3 pieces',15,700,'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10018.png','',''),
(10019,'Manequin','kitchen, living room, bedroom','decoration','wood','beige','able to shift shapes',40,350,'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10019.png','',''),
(10020,'Clock','kitchen, living room, bedroom','decoration','plastic','red','on wall',30,350,'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10020.png','',''),
(10021,'Candle','living room, bedroom, bathroom','decoration','glass','white','scented',10,250,'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10021.png','',''),
(10022,'Plant','kitchen, living room, bedroom, bathroom','decoration','polyester','green','artificial plant',25,120,'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10022.png','',''),
(10023,'Floor Lamp','kitchen, living room, bedroom','lighting','metal','black','on-stand',25,3500,'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10023.png','',''),
(10024,'Chandelier','kitchen, living room, bedroom, bathroom','lighting','metal','green','Cord length is 1.8 m',25,5000,'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10024.png','',''),
(10025,'Wall Lamp','kitchen, living room, bedroom, bathroom','lighting','metal, polyester','white, yellow','Chargable',25,4000,'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10025.png','',''),
(10026,'Table Lamp','living room, bedroom','lighting','metal','blue','25 cm',25,3500,'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10026.png','',''),
(10027,'Berlin Sofa','living room','sofa','polyester','blue','corner bed sofa, 3 seats',15,15000,'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10027.png','',''),
(10028,'Amsterdam Sofa','living room, bedroom','sofa','polyester','green','1 seat',25,7000,'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10028.png','',''),
(10029,'Rome Sofa','living room','sofa','cotton','orange','3 seat',7,40000,'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10029.png','',''),
(10030,'Paris Sofa','living room','sofa','cotton','red','corner bed sofa, 4 seats',5,60000,'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10030.png','',''),
(10031,'Paris Unit','living room','tv unit','wood','white','with book shelfs',15,35000,'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10031.png','',''),
(10032,'Rome Unit','living room','tv unit','wood','blue','with closed cabinet doors',20,18000,'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10032.png','',''),
(10033,'Berlin Unit','living room','tv unit','metal','black','easy to arrange cords and access power sockets',10,20000,'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10033.png','',''),
(10034,'London Coffee Table','living room','side table','wood','brown','extra shelf under table, 180 cm',15,22000,'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10034.png','',''),
(10035,'Istanbul Coffee Table','living room, bedroom','side table','plastic','orange','70 cm',30,4000,'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10035.png','',''),
(10036,'Budapest Coffee Table','living room, bedroom','side table','metal','green','50 cm',40,7000,'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10036.png','',''),
(10037,'New York Coffee Table','living room','side table','plastic','yellow, white','nested side table',25,5000,'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10037.png','',''),
(10038,'Wave Pillow','living room, bedroom','pillow','cotton','blue, white','square',70,250,'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10038.png','',''),
(10039,'Sweet Pillow','living room, bedroom','pillow','cotton','pink','round, velvet',50,350,'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10039.png','',''),
(10040,'Sun Pillow','living room, bedroom','pillow','polyester','yellow','rectangle',65,170,'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10040.png','',''),
(10041,'Rainbow Rug','living room, bedroom','rug','cotton','yellow, pink, blue, brown, purple, green','colorful, no swipe',25,7800,'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10041.png','',''),
(10042,'Autumn Rug','living room, bedroom, kitchen','rug','cotton','brown','no stain, waterproof',85,3400,'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10042.png','',''),
(10043,'Paris Rug','living room, bedroom, kitchen','rug','polyester','pink, red','no swipe',50,1600,'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10043.png','',''),
(10044,'Cloud Rug','living room, bedroom','rug','polyester','white','puffy, soft',40,3800,'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10044.png','',''),
(10045,'New York Curtain','living room, bedroom','curtain','polyester','black','blackout, 200x250 cm',35,4400,'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10045.png','',''),
(10046,'Rome Curtain','living room, bedroom','curtain','cotton','pink','background, 200x250 cm',40,5000,'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10046.png','',''),
(10047,'Light Free Curtain','living room, bedroom','curtain','cotton','white','blind, 180x220 cm',75,3700,'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10047.png','',''),
(10048,'Cream Curtain','living room, bedroom','curtain','polyester','beige','folded, 180x220 cm',25,4800,'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10048.png','',''),
(10049,'Rome Bed','bedroom','bed','wood','brown','storage, double sided, 160x200 cm',15,17000,'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10049.png','',''),
(10050,'Prag Bed','bedroom','bed','wood','white','single bed, 90x200 cm',25,6000,'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10050.png','',''),
(10051,'Berlin Bed','bedroom','bed','metal','black','double sided, 160x200 cm',20,7500,'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10051.png','',''),
(10052,'Bunk Bed','bedroom','bed','metal','gray','bunk bed, 90x200 cm, 2 single beds',10,9500,'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10052.png','',''),
(10053,'Milano Wardrobe','bedroom','wardrobe','wood','yellow, white','4 doors, 200x350x50 cm, 5 shelfs',35,25000,'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10053.png','',''),
(10054,'Berlin Wardrobe','bedroom','wardrobe','wood','black','sliding doors, 7 shelfs, 200x400x60 cm',40,45000,'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10054.png','',''),
(10055,'Corner Wardrobe','bedroom','wardrobe','wood','gray','corner wardrobe, 160/110x230x40 cm',20,35000,'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10055.png','',''),
(10056,'Amsterdam Wardrobe','bedroom','wardrobe','wood','white','250x200x50 cm, open wardrobe, 7 shelfs',70,15000,'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10056.png','',''),
(10057,'Strong Box','bedroom, bathroom, kitchen','box','metal','black','no lid',30,600,'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10057.png','',''),
(10058,'Paris Box','bedroom, bathroom, kitchen, living room','box','polyester','white','has 2 shelfs',25,750,'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10058.png','',''),
(10059,'Baby Box','bedroom, bathroom, living room','box','cotton','beige','no lid',35,550,'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10059.png','',''),
(10060,'Toy Box','bedroom, bathroom, kitchen','box','plastic','blue','with lid',70,450,'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10060.png','',''),
(10061,'Work Box','bedroom, bathroom, kitchen','box','plastic','white','with lid',80,350,'https://raw.githubusercontent.com/aslikoturoglu/CS308-Project/main/project_pictures/10061.png','','');
